### ISSUE TITLE
ecl in Noetic

### ISSUE THREAD

**Issue by fmrico** [stonier/ecl_core#104] opened 2020-05-24 06:32 UTC
Dear @stonier 

There will be a release for Noetic? I am using kobuki, and it depends on ecl :)

Thanks!!

**Comment by stonier** [comment] 2020-06-03 13:20
On their way

**Comment by m2kulkarni** [comment] 2020-06-05 08:17
How can i build such that it is comaptible with noetic?

**Comment by stonier** [comment] 2020-06-06 14:45
I haven't tried it myself but you should be able to just drop ecl_tools, ecl_lite, sophus and ecl_core into your workspace like any other ros repository.

**Comment by stonier** [comment] 2020-06-06 14:47
Tracking RosDistro PR's

* [ecl_tools](https://github.com/ros/rosdistro/pull/25074)
* [ecl_lite](https://github.com/ros/rosdistro/pull/25304)
* [sophus](https://github.com/ros/rosdistro/pull/25361)
* ecl_core ... coming

**Comment by m2kulkarni** [comment] 2020-06-06 16:29
Hey, so i tried doing that. I cloned this repository into my workspace and then did catkin_make but there is a error `Error: Packages with unknown build types exist
Can not build workspace with packages of unknown build_type`. 
![Screenshot from 2020-06-06 21-56-03](https://user-images.githubusercontent.com/56233197/83949364-ffba6380-a840-11ea-9944-cbee1e3e6417.png)

**Comment by stonier** [comment] 2020-06-06 16:52
I suspect you've got the wrong branches. The default branch for ecl repositories now targets ROS2. 

This [ecl.repos](https://github.com/stonier/repos_index/blob/devel/noetic/ecl.repos) should work for noetic, or at least give you the hint. I don't have noetic installed yet, so let me know how it goes.

**Comment by m2kulkarni** [comment] 2020-06-07 17:00
Hey, so basically I am trying to run [Champ ](https://github.com/chvmp/champ). In that it automatically clones yocs_velocity_simulator. I saw your comment on yocs too. 
![Screenshot from 2020-06-07 22-25-19](https://user-images.githubusercontent.com/56233197/83974926-635e9280-a90e-11ea-9ce9-49ee79911454.png)

Also as you suggested, i tried cloning the melodic release version but the errors persisted

**Comment by stonier** [comment] 2020-06-07 18:07
That's a fairly generic message that usually indicates it's not around or has been skipped because catkin doesn't know what to do with it. You'll have to dig around earlier in the build output to grokk that. Unfortunately, I don't have a `20.04` installation yet, so can't try to reproduce here.

If there is something peculiar to `20.04`, I'll get some signal from the build farm once those PR's get into `rosdistro`.

**Comment by stonier** [comment] 2020-06-08 16:46
Looks like I need a noetic install after all - there are some critical [warnings turning into errors](https://mail.google.com/mail/u/0/#inbox/FMfcgxwHNgldczfRQMQBSCrvQmnmjBbW) being caught on 20.04 that weren't being caught on 18.04 :)

**Comment by m2kulkarni** [comment] 2020-06-08 17:02
Hey, sorry for not replying. It actually did build successfully. I guess sopheus wasnt working with other packages so i built it in another workspace and ecl_toos, ecl_core and ecl_lite in another. Thankully now there are no errors when i try to catkin_make champ. BUT the models are still not working, but i guess that has nothing to do with ecl.(i have posted that as another [issue](https://github.com/chvmp/champ/issues/3)

Thanks for the replies, it helped me figure out things. You may go ahead and close the issue. Thanks again

**Comment by stonier** [comment] 2020-06-08 17:48
Ah, the release version in CI is setting stricter build flags I expect. And yes, I forgot with catkin you need sophus (pure cmake project) in an underlying workspace. Good to hear it works.

Keeping this open - still tracking the noetic release.

**Comment by stonier** [comment] 2020-08-28 14:22
Debs are in.

**Closed as completed by stonier** 2020-08-28 14:22 UTC
Labels: type: infra
